version: "3.5"
services:
  sepolia-erigon:
    image: "sepolia-erigon.sepolia-erigon.dnp.dappnode.eth:0.1.0"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v2.59.1
    ports:
      - "35416:35416/tcp"
      - "35416:35416/udp"
      - "47282:47282/tcp"
      - "47282:47282/udp"
      - "9113:9113/udp"
      - "9115:9115/tcp"
    volumes:
      - "data:/home/sepolia-erigon/.local/share"
    environment:
      P2P_PORT: 35416
      CAPLIN_P2P_PORT: 9113
      CAPLIN_P2P_TCP_PORT: 9115
      EXTRA_OPTS: "--http.api=eth,erigon,web3,net,debug,trace"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 32768M
volumes:
  data: {}
